DROP TABLE IF EXISTS entity_books;

CREATE TABLE entity_books (id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   tile VARCHAR(50) NOT NULL,
   author VARCHAR(50) NOT NULL,
   gender VARCHAR(255) NOT NULL CHECK (
                gender IN ('FANTASY','ACTION','SCIENCE_FICTION',
                'SCIENCE','ADVENTURE','ROMANCE','BIOGRAPHY',
                'HISTORY','HORROR','NON_FICTION')),
   price FLOAT(53) NOT NULL,
   pages INTEGER NOT NULL,
   available BOOLEAN NOT NULL,
   publisher VARCHAR(255) NOT NULL,
   PRIMARY KEY (id, gender)) PARTITION BY LIST(gender);

CREATE TABLE part_books_gender_fantasy PARTITION OF entity_books FOR VALUES IN ('FANTASY');
CREATE TABLE part_books_gender_action PARTITION OF entity_books FOR VALUES IN ('ACTION');
CREATE TABLE part_books_gender_sciencefiction PARTITION OF entity_books FOR VALUES IN ('SCIENCE_FICTION');
CREATE TABLE part_books_gender_science PARTITION OF entity_books FOR VALUES IN ('SCIENCE');
CREATE TABLE part_books_gender_adventure PARTITION OF entity_books FOR VALUES IN ('ADVENTURE');
CREATE TABLE part_books_gender_romance PARTITION OF entity_books FOR VALUES IN ('ROMANCE');
CREATE TABLE part_books_gender_biography PARTITION OF entity_books FOR VALUES IN ('BIOGRAPHY');
CREATE TABLE part_books_gender_history PARTITION OF entity_books FOR VALUES IN ('HISTORY');
CREATE TABLE part_books_gender_horror PARTITION OF entity_books FOR VALUES IN ('HORROR');
CREATE TABLE part_books_gender_nonfiction PARTITION OF entity_books FOR VALUES IN ('NON_FICTION');
