create table "rs_users-roles" (roleid bigint not null, userid bigint not null, primary key (roleid, userid));
create table "entity-user" (account_no_expired boolean not null, account_no_locked boolean not null, credentials_no_expired boolean not null, is_enabled boolean not null, id bigint generated by default as identity, email varchar(255) not null unique, name varchar(255), password varchar(255) not null, primary key (id));
create table entity_privileges (id bigint generated by default as identity, privilege_name varchar(255) check (privilege_name in ('GET','POST','DELETE','PATCH','PUT','HEAD','OPTIONS')), primary key (id));
create table entity_roles (id bigint generated by default as identity, role_name varchar(255) check (role_name in ('READER','DRIVER','MECHANIC','ADMIN','DEVELOPER')), primary key (id));
create table rs_roles_privileges (privilegeid bigint not null, roleid bigint not null, primary key (privilegeid, roleid));
alter table if exists "rs_users-roles" add constraint FK10iwkrw0dylfgqopcwny0fb0h foreign key (roleid) references entity_roles;
alter table if exists "rs_users-roles" add constraint FKaw5irjxm161lvaiav36nstfne foreign key (userid) references "entity-user";
alter table if exists rs_roles_privileges add constraint FK4goks98ee1ryn54sguwl0b2bn foreign key (privilegeid) references entity_privileges;
alter table if exists rs_roles_privileges add constraint FK4c0ar1q4be9783cfhd3178gpp foreign key (roleid) references entity_roles;